name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abaa7e2e61083cf4b9ee184d18fd887bfddabe1adfd384e514247c7de92450e1"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
