name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90099fede4d738284b914f40fcb53086519fc5925ce16b2a26443fe1a842d22c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
