name = "gsmp5"
author = "GSMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ffd69e359c6274f6f82784b138cc7db9b7efffc193e37528d0fafb18d00d0eb"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
